version: '3'

services:

        app:
                build: ./fabtest/
                ports:
                  - "8080:8080"
                volumes:
                  - data2:/home/work
                tty: true

        rp:
                build: ./nginx-rp/
                ports:
                  - "80:80"

        pg:
                build: ./postgres/
                ports:
                  - "5432:5432"
                environment:
                        - POSTGRES_PASSWORD=password
                volumes:
                        - postgres_data:/var/lib/postgresql/

volumes:
        data2:
        postgres_data:
