version: '3'

services:

        app:
                build: ./fabtest/
                ports:
                  - "8080:8080"
                volumes:
                  - data2:/home/work
                networks:
                        app_net:
                                ipv4_address: 172.21.0.6
                tty: true
                # command: python run.py

        rp:
                build: ./nginx-rp/
                ports:
                  - "80:80"

        pg:
                build: ./postgres/
                ports:
                  - "5432:5432"
                environment:
                        - POSTGRES_PASSWORD=password
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                networks:
                        app_net:
                                ipv4_address: 172.21.0.5

volumes:
        data2:
        postgres_data:

networks:
        app_net:
                ipam:
                        driver: default
                        config:
                                - subnet: "172.21.0.0/24"
